# Generated by Django 4.0.5 on 2022-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_sources_ldap', '0002_auto_20211203_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsource',
            name='ciphers',
            field=models.TextField(blank=True, default='ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:DHE+CHACHA20:ECDH+AESGCM:DH+AESGCM:ECDH+AES:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!eNULL:!MD5:!DSS', help_text='Ciphers you want to use. (e.g ECDHE+AESGCM:ECDHE+CHACHA20)'),
        ),
    ]
